import { Inter } from "next/font/google";
import { WebSocketProvider } from './context/WebSocketContext'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <WebSocketProvider>
        <body className={inter.className}>{children}</body>
      </WebSocketProvider>
    </html>
  );
}
